apiVersion: apps/v1
kind: Deployment
metadata:
  name: got-to-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: got-to-app
  template:
    metadata:
      labels:
        app: got-to-app
    spec:
      containers:
        - name: got-to-app
          image: fostoq/reg-app:1.0.0-26
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080