apiVersion: v1
kind: Service
metadata:
  name: got-to-app-service
  labels:
    app: got-to-app
spec:
  selector:
    app: got-to-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer